strict-sigcheck = false

[YouTube-Stable]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[YouTube-Stable.patches]
"github:MorpheApp/morphe-patches" = []

[YT-Music-Stable]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "both"

[YT-Music-Stable.patches]
"github:MorpheApp/morphe-patches" = []

[Reddit-Stable]
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[Reddit-Stable.patches]
"github:MorpheApp/morphe-patches" = []

[YouTube-Experimental]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
version = "21.25.523"
patcher-args = "-e 'Change header' -Ocustom=icons/YouTube/header -e 'Custom branding' -OcustomIcon=icons/YouTube/branding -OcustomName='YouTube Morphe'"

[YouTube-Experimental.patches]
"github:MorpheApp/morphe-patches" = []

[YT-Music-Experimental]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "both"
version = "9.24.51"
patcher-args = "-e 'Change header' -Ocustom=icons/Music/header -e 'Custom branding' -OcustomIcon=icons/Music/branding -OcustomName='Music Morphe'"

[YT-Music-Experimental.patches]
"github:MorpheApp/morphe-patches" = []

[Reddit-Experimental]
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
version = "2026.25.0"
patcher-args = "-e 'Custom branding name for Reddit' -OappName='Reddit Morphe'"
